#!/usr/bin/env bash
set -euo pipefail

# Compatibility smoke test. V2 traffic is generated by the catalog-backed runner
# so this script cannot drift into unsupported endpoints or marker-based alerts.
ATTACKER_CONTAINER="${ATTACKER_CONTAINER:-soc_attacker_v2}"

docker exec "$ATTACKER_CONTAINER" attackctl run-batch \
  RECON-03 WEB-04 WEB-06 WEB-08 WEB-09 AUTH-12 \
  --pause "${SCENARIO_PAUSE:-0.5}"

cat <<'MSG'

Behavioral smoke scenarios were sent. Check:
  ./scripts/show-custom-alerts.sh

Then search Wazuh for:
  rule.groups: suricata
  data.alert.signature_id: 1001001 to 1001099
MSG
