#!/usr/bin/env python3
"""Generate the A2 scenario tree and isolated custom Suricata ruleset."""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[3]
SCENARIO_ROOT = ROOT / "soc-attacker-advanced-v3.0.0" / "scenarios" / "a2"
RULE_OUTPUT = ROOT / "sensor" / "a2.rules"
SID_START = 1002001
records: list[dict[str, Any]] = []


# OWASP CRS provenance. A subset of the A2 rules adapts the detection
# condition of an OWASP Core Rule Set rule; the referenced CRS rule id is
# recorded in the Suricata rule metadata so the generated rule keeps an
# auditable external reference without renaming the behavioural message.
CRS_VERSION = "4.29.0"
CRS_LEGACY_VERSION = "3.3.7"


def crs_metadata(rule_id: str, version: str, strength: str) -> str:
    """Render the ``metadata`` clause that records the CRS reference."""
    return (
        f"owasp_crs_rule {rule_id}, owasp_crs_ver {version}, "
        f"owasp_crs_strength {strength}"
    )


def crs_kwargs(reference: tuple[str, str, str] | None) -> dict[str, Any]:
    """Translate a CRS reference tuple into ``add`` keyword arguments."""
    if reference is None:
        return {}
    rule_id, version, strength = reference
    return {
        "metadata": crs_metadata(rule_id, version, strength),
        "rule_source": "owasp_crs",
    }


# Keys that only exist in the scenario manifest, never in catalog.json.
YAML_ONLY_KEYS = {"rule", "rule_source", "source_type", "reference"}


def add(
    technique: str, tactic: str, name: str, description: str,
    kind: str, params: dict[str, Any], header: str, options: str,
    *, expected_status: str = "mapped", revision: int = 1,
    classtype: str = "misc-activity", metadata: str | None = None,
    rule_source: str = "custom", source_type: str = "custom",
    reference: str = "Manual network-observable lab scenario",
) -> None:
    sid = SID_START + len(records)
    index = 1 + sum(item["technique"] == technique for item in records)
    scenario_id = f"A2-{technique}-{index:02d}"
    rule_name = "LAB " + name
    metadata_clause = f"metadata:{metadata}; " if metadata else ""
    rule = (
        f'{header} (msg:"{rule_name}"; {options} '
        f'{metadata_clause}classtype:{classtype}; sid:{sid}; rev:{revision};)'
    )
    records.append({
        "id": scenario_id,
        "sid": sid,
        "technique": technique,
        "tactic": tactic,
        "rule_name": rule_name,
        "description": description,
        "kind": kind,
        "params": params,
        "rule": rule,
        "expected_status": expected_status,
        "rule_source": rule_source,
        "source_type": source_type,
        "reference": reference,
    })


# T1046: internal-to-internal probes generated by the lab backend.
add("T1046", "TA0007", "Internal Common Service Sweep", "Probe a fixed set of common TCP services from one internal lab host to another.", "internal_discovery", {"profile": "tcp-common"}, "alert tcp 172.29.0.2 any -> 172.29.0.4 [21,22,23,25,80,443]", "flags:S; flow:stateless; detection_filter:track by_src,count 4,seconds 10;")
add("T1046", "TA0007", "Internal Administrative Port Sweep", "Probe administrative and database service ports inside the lab network.", "internal_discovery", {"profile": "tcp-admin"}, "alert tcp 172.29.0.2 any -> 172.29.0.4 [445,1433,3000,8080,9200]", "flags:S; flow:stateless; detection_filter:track by_src,count 4,seconds 10;")
add("T1046", "TA0007", "Internal UDP Service Probe", "Send harmless UDP discovery datagrams to internal service ports.", "internal_discovery", {"profile": "udp-service"}, "alert udp 172.29.0.2 any -> 172.29.0.4 [53,67,123,161,1900]", "flow:stateless; content:\"SOC-LAB-SERVICE-PROBE|3a|udp-service\"; detection_filter:track by_src,count 3,seconds 10;")

# T1078: successful use of four credential forms, confirmed in the response.
for channel, title in [("bearer", "Successful Bearer Session Use"), ("session", "Successful Web Session Reuse"), ("api-key", "Successful API Credential Use"), ("basic", "Successful Basic Credential Use")]:
    add("T1078", "TA0001", title, f"Use a valid lab {channel} credential and observe an authenticated response.", "valid_auth", {"channel": channel}, "alert http $HOME_NET any -> $EXTERNAL_NET any", f'flow:established,to_client; http.response_body; content:"|22|authenticated|22 3a|true"; nocase; content:"|22|channel|22 3a 22|{channel}|22|"; nocase;')

# T1189: malicious-looking content delivered in an HTTP response to the client.
driveby = [
    ("Fake Verification Page Delivery", "urgent verification content", "<div class=urgent-verification>Confirm browser access to continue</div>"),
    ("Hidden Loader Script Delivery", "a hidden client-side loader", "<script>window.hiddenLoader='https://cdn.invalid/stage.js'</script>"),
    ("Deceptive Browser Update Delivery", "a fake browser update prompt", "Browser update required. Download secure-browser-update.bin to continue"),
]
for title, description, payload in driveby:
    token = payload.split("'")[-2] if "'" in payload else ("secure-browser-update.bin" if "secure-browser" in payload else "urgent-verification")
    add("T1189", "TA0001", title, f"Return a harmless response containing {description}.", "driveby_response", {"payload": payload}, "alert http $HOME_NET any -> $EXTERNAL_NET any", f'flow:established,to_client; http.response_body; content:"{token}"; nocase;')

# T1595: generic active reconnaissance observables.
active = [
    ("Sequential Public Service Probes", "active_port_scan", {}, "alert tcp $EXTERNAL_NET any -> $HOME_NET [21,22,23,25,443,8080,9200]", "flags:S; flow:stateless; detection_filter:track by_src,count 5,seconds 10;", None),
    ("HTTP Capability Assessment", "http_probe", {"method": "OPTIONS", "path": "/", "user_agent": "network-audit-client/1.0"}, "alert http $EXTERNAL_NET any -> $HOME_NET any", 'flow:established,to_server; http.method; content:"OPTIONS"; http.user_agent; content:"network-audit-client/1.0";', ("913100", CRS_VERSION, "semantic")),
    ("Service Banner Identification", "http_probe", {"method": "HEAD", "path": "/", "user_agent": "service-banner-audit/1.0"}, "alert http $EXTERNAL_NET any -> $HOME_NET any", 'flow:established,to_server; http.method; content:"HEAD"; http.user_agent; content:"service-banner-audit/1.0";', ("913100", CRS_VERSION, "semantic")),
    ("Infrastructure Metadata Probe", "http_probe", {"method": "GET", "path": "/robots.txt", "user_agent": "infrastructure-inventory/1.0"}, "alert http $EXTERNAL_NET any -> $HOME_NET any", 'flow:established,to_server; http.uri; content:"/robots.txt"; http.user_agent; content:"infrastructure-inventory/1.0";', ("913100", CRS_VERSION, "semantic")),
    ("Legacy Method Reconnaissance", "raw_http_probe", {"method": "TRACE"}, "alert http $EXTERNAL_NET any -> $HOME_NET any", 'flow:established,to_server; http.method; content:"TRACE";', ("911100", CRS_VERSION, "literal")),
]
for title, kind, params, header, options, crs in active:
    add("T1595", "TA0043", title, "Perform a bounded reconnaissance probe against the isolated public lab gateway.", kind, params, header, options, **crs_kwargs(crs))

# T1595.001: the gateway owns five lab-only aliases, allowing a real multi-IP sweep.
for port, label in [(80, "Web Address Range Sweep"), (443, "TLS Address Range Sweep"), (22, "Remote Access Address Sweep"), (8080, "Alternate Web Address Sweep"), (3000, "Application Address Range Sweep")]:
    add("T1595.001", "TA0043", label, f"Probe TCP port {port} across five isolated gateway IP aliases.", "ip_block_scan", {"port": port}, f"alert tcp $EXTERNAL_NET any -> [172.29.0.20,172.29.0.21,172.29.0.22,172.29.0.23,172.29.0.24] {port}", "flags:S; flow:stateless; detection_filter:track by_src,count 4,seconds 15;")

# T1595.002: vulnerability and exposure assessment requests.
vuln = [
    ("Template Scanner Request", "GET", "/", "Nuclei - Open-source project", None, 'http.user_agent; content:"Nuclei - Open-source project";', ("913100", CRS_VERSION, "literal")),
    ("CVE Exposure Check Request", "GET", "/.well-known/security.txt?cve_check=CVE-2021-44228", "Mozilla/5.0", None, 'http.uri; content:"cve_check=CVE-2021-44228"; nocase;', None),
    ("WebDAV Capability Check", "OPTIONS", "/webdav/", "configuration-audit/1.0", None, 'http.method; content:"OPTIONS"; http.uri; content:"/webdav/";', None),
    ("Graph Query Schema Probe", "POST", "/graphql", "schema-audit/1.0", '{"query":"{__schema{types{name}}}"}', 'http.uri; content:"/graphql"; http.request_body; content:"__schema";', None),
    ("Server Status Exposure Check", "GET", "/server-status?auto", "version-audit/1.0", None, 'http.uri; content:"/server-status?auto";', None),
]
for title, method, path, ua, body, match, crs in vuln:
    add("T1595.002", "TA0043", title, "Send a bounded request intended to assess a specific exposed feature or weakness.", "vuln_scan", {"method": method, "path": path, "user_agent": ua, "body": body}, "alert http $EXTERNAL_NET any -> $HOME_NET any", f"flow:established,to_server; {match}", **crs_kwargs(crs))

# T1595.003: five distinct dictionary-derived resource families.
wordlists = [
    ("Administrative Resource Enumeration", ["/admin", "/administrator", "/admin/login", "/manage", "/console", "/controlpanel"], r"/^\/(?:admin|administrator|manage|console|controlpanel)/", None),
    ("Backup Artifact Enumeration", ["/backup.zip", "/site.tar.gz", "/database.bak", "/dump.sql", "/www.zip", "/archive.old"], r"/(?:backup|site|database|dump|www|archive).*(?:zip|gz|bak|sql|old)/", ("920440", CRS_VERSION, "literal")),
    ("Repository Metadata Enumeration", ["/.git/config", "/.svn/entries", "/.hg/store", "/.env", "/config.yml", "/settings.json"], r"/^\/(?:\.git|\.svn|\.hg|\.env|config|settings)/", ("930130", CRS_VERSION, "literal")),
    ("API Documentation Enumeration", ["/swagger", "/swagger-ui", "/openapi.json", "/api-docs", "/graphql", "/redoc"], r"/^\/(?:swagger|openapi|api-docs|graphql|redoc)/", None),
    ("CMS Resource Enumeration", ["/wp-admin", "/wp-login.php", "/joomla", "/drupal", "/xmlrpc.php", "/user/login"], r"/^\/(?:wp-admin|wp-login|joomla|drupal|xmlrpc|user\/login)/", None),
]
for title, paths, regex, crs in wordlists:
    threshold_count = 3 if title == "CMS Resource Enumeration" else 4
    revision = 2 if title == "CMS Resource Enumeration" else 1
    add("T1595.003", "TA0043", title, "Enumerate a bounded dictionary of related web resources on the local gateway.", "wordlist_scan", {"paths": paths}, "alert http $EXTERNAL_NET any -> $HOME_NET any", f'flow:established,to_server; http.uri; pcre:"{regex}i"; detection_filter:track by_src,count {threshold_count},seconds 15;', revision=revision, **crs_kwargs(crs))

channels = ["json", "form", "basic", "token", "pin"]
channel_titles = {"json": "JSON", "form": "Form", "basic": "Basic", "token": "Token", "pin": "PIN"}

# T1110 parent: repeated failures without stable account/password cardinality.
for channel in channels:
    add("T1110", "TA0006", f"Repeated {channel_titles[channel]} Authentication Failures", "Submit multiple failed authentication attempts with both identities and credentials varying.", "brute_parent", {"channel": channel}, "alert http $EXTERNAL_NET any -> $HOME_NET any", f'flow:established,to_server; http.method; content:"POST"; http.uri; content:"/lab/auth/{channel}"; detection_filter:track by_src,count 5,seconds 15;')

# T1110.001: one identity, many candidate credentials.
for channel in channels:
    add("T1110.001", "TA0006", f"Repeated {channel_titles[channel]} Credential Guesses", "Try multiple different credentials against one fixed lab identity.", "password_guess", {"channel": channel}, "alert http $EXTERNAL_NET any -> $HOME_NET any", f'flow:established,to_server; http.uri; content:"/lab/auth/{channel}"; http.request_body; content:"fixed-user@soc.lab"; nocase;')

# T1110.003: one credential candidate across many identities.
for channel in channels:
    add("T1110.003", "TA0006", f"Shared {channel_titles[channel]} Credential Across Accounts", "Try one fixed credential against multiple distinct lab identities.", "password_spray", {"channel": channel}, "alert http $EXTERNAL_NET any -> $HOME_NET any", f'flow:established,to_server; http.uri; content:"/lab/auth/{channel}"; http.request_body; content:"Shared-Password-1!"; nocase;')

# T1505.003: access to five web-shell-shaped resources.
shells = [
    ("Suspicious PHP Command Endpoint Access", "GET", "/uploads/system.php?cmd=id", None, 'http.uri; content:"/uploads/system.php?cmd=";', ("932160", CRS_VERSION, "literal")),
    ("Suspicious JSP Command Endpoint Access", "POST", "/images/cache.jsp", "cmd=whoami", 'http.uri; content:"/images/cache.jsp"; http.request_body; content:"cmd=whoami";', ("932160", CRS_VERSION, "literal")),
    ("Suspicious ASPX Execution Endpoint Access", "GET", "/aspnet_client/update.aspx?action=exec", None, 'http.uri; content:"/aspnet_client/update.aspx?action=exec";', None),
    ("Hidden Script Control Request", "POST", "/cgi-bin/.maintenance.pl", "action=command&value=id", 'http.uri; content:"/cgi-bin/.maintenance.pl"; http.request_body; content:"action=command";', ("932160", CRS_VERSION, "literal")),
    ("Plugin Command Console Access", "GET", "/plugins/healthcheck.phtml?c=whoami", None, 'http.uri; content:"/plugins/healthcheck.phtml?c=";', ("932160", CRS_VERSION, "literal")),
]
for title, method, path, body, match, crs in shells:
    add("T1505.003", "TA0003", title, "Access a harmless web-shell-shaped path using a command-control parameter.", "webshell_access", {"method": method, "path": path, "body": body}, "alert http $EXTERNAL_NET any -> $HOME_NET any", f"flow:established,to_server; {match}", **crs_kwargs(crs))

# T1499: bounded application-layer request surges. The burst-threshold shape is
# adapted from the CRS request-burst DoS counter, which only exists in CRS 3.x.
endpoint_dos = [
    ("Rapid Rendering Request Burst", "normal_get", 'http.uri; content:"/lab/normal?work=render";', ("912170", CRS_LEGACY_VERSION, "semantic")),
    ("Repeated Aggregation Submissions", "normal_post", 'http.method; content:"POST"; http.uri; content:"/lab/normal"; http.request_body; content:"aggregate";', ("912170", CRS_LEGACY_VERSION, "semantic")),
    ("Search Endpoint Request Surge", "search", 'http.uri; content:"/rest/products/search?q=resource-intensive";', ("912170", CRS_LEGACY_VERSION, "semantic")),
    ("Authentication Endpoint Request Surge", "auth", 'http.method; content:"POST"; http.uri; content:"/lab/auth/json";', ("912170", CRS_LEGACY_VERSION, "semantic")),
    ("Multipart Processing Request Surge", "upload", 'http.method; content:"POST"; http.uri; content:"/lab/upload";', ("912170", CRS_LEGACY_VERSION, "semantic")),
]
for title, profile, match, crs in endpoint_dos:
    # Keep the threshold high enough to represent a burst, while allowing for
    # host clock corrections that can split one monotonic run across wall-clock
    # seconds in containerized Windows environments.
    add("T1499", "TA0040", title, "Send a small bounded burst to one application endpoint without exhausting host resources.", "endpoint_dos", {"profile": profile, "count": 12}, "alert http $EXTERNAL_NET any -> $HOME_NET any", f"flow:established,to_server; {match} detection_filter:track by_src,count 10,seconds 60;", **crs_kwargs(crs))

# T1071.001: five HTTP command-channel request shapes.
for profile, method in [("telemetry", "POST"), ("checkin", "GET"), ("heartbeat", "POST"), ("sync", "PUT"), ("tasks", "POST")]:
    add("T1071.001", "TA0011", f"Periodic Web {profile.title()} Traffic", "Generate six periodic HTTP requests from the lab backend to the isolated command sink.", "web_c2", {"profile": profile}, "alert http $HOME_NET any -> $HOME_NET any", f'flow:established,to_server; http.method; content:"{method}"; http.uri; content:"/__soc_internal__/c2/{profile}"; detection_filter:track by_src,count 3,seconds 30;')

# T1659: explicit intermediary-origin response modifications.
content_profiles = [
    ("Unexpected Verification Banner Insertion", "banner", "urgent-notice"),
    ("Unexpected External Script Insertion", "script", "inserted-loader.js"),
    ("Unexpected Hidden Frame Insertion", "iframe", "embedded-content"),
    ("Unexpected Configuration Redirection", "config", "redirect.invalid/modified"),
    ("Unexpected Download Link Insertion", "download", "browser-update.bin"),
]
for title, profile, token in content_profiles:
    add("T1659", "TA0001", title, "Return content explicitly marked as inserted by the controlled intermediary simulation.", "content_injection", {"profile": profile}, "alert http $HOME_NET any -> $EXTERNAL_NET any", f'flow:established,to_client; http.response_header; content:"X-SOC-Content-Origin|3a| intermediary"; nocase; http.response_body; content:"{token}"; nocase;')

# T1498: small UDP bursts represent network-layer DoS attempts without impact.
for port, title in [(53, "High Rate DNS Service Traffic"), (123, "High Rate Time Service Traffic"), (161, "High Rate Management Service Traffic"), (1900, "High Rate Discovery Service Traffic"), (11211, "High Rate Cache Service Traffic")]:
    add("T1498", "TA0040", title, f"Send twenty small UDP datagrams to lab port {port}; volume is intentionally harmless.", "network_dos", {"port": port, "count": 20}, f"alert udp $EXTERNAL_NET any -> $HOME_NET {port}", "flow:stateless; detection_filter:track by_src,count 12,seconds 5;")

# T1095: opaque non-HTTP TCP/UDP messages.
non_app = [
    ("Opaque TCP Node Greeting", "tcp", 80, "50494e47004e4f4445", 'content:"|50 49 4e 47 00 4e 4f 44 45|";'),
    ("Length Prefixed TCP Beacon", "tcp", 80, "0008424541434f4e3031", 'content:"|00 08 42 45 41 43 4f 4e 30 31|";'),
    ("Plain TCP Heartbeat Frame", "tcp", 80, "4845415254424541547c686f73747c310a", 'content:"|48 45 41 52 54 42 45 41 54 7c 68 6f 73 74 7c 31|";'),
    ("Opaque UDP Node Greeting", "udp", 4444, "4e4f44452d48454c4c4fff", 'content:"|4e 4f 44 45 2d 48 45 4c 4c 4f ff|";'),
    ("Binary UDP Synchronization Frame", "udp", 5555, "53594e430102", 'content:"|53 59 4e 43 01 02|";'),
]
for title, protocol, port, payload_hex, match in non_app:
    add("T1095", "TA0011", title, "Send an opaque application-independent frame inside the isolated lab network.", "non_app", {"protocol": protocol, "port": port, "payload_hex": payload_hex}, f"alert {protocol} $EXTERNAL_NET any -> $HOME_NET {port}", f"flow:stateless; {match}")


def yaml_text(record: dict[str, Any]) -> str:
    return f"""id: {record['id']}
name: {record['rule_name'][4:]}
description: {record['description']}
mitre:
  tactic_id:
    - {record['tactic']}
  technique_id:
    - {record['technique']}
suricata:
  expected_sid:
    - {record['sid']}
  rule_name: {record['rule_name']}
  rule_source: {record['rule_source']}
source:
  container: soc_attacker_v2
  type: {record['source_type']}
  reference: {record['reference']}
target:
  container: soc_gateway
  port: 80
execution:
  action_id: A2-{record['sid']}
expected:
  minimum_alerts: 1
  ingestion_required: true
  mapping_required: true
  mapping_status: {record['expected_status']}
timeout: 40
"""


def main() -> None:
    if SCENARIO_ROOT.exists():
        shutil.rmtree(SCENARIO_ROOT)
    SCENARIO_ROOT.mkdir(parents=True)
    for record in records:
        directory = SCENARIO_ROOT / record["technique"] / record["id"]
        directory.mkdir(parents=True)
        (directory / "scenario.yaml").write_text(yaml_text(record), encoding="utf-8")
        (directory / "rule.rules").write_text(record["rule"] + "\n", encoding="utf-8")
    catalog = [
        {key: value for key, value in record.items() if key not in YAML_ONLY_KEYS}
        for record in records
    ]
    (SCENARIO_ROOT / "catalog.json").write_text(
        json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    RULE_OUTPUT.write_text(
        "# A2 custom rules. Generated by src/tools/generate_a2.py.\n"
        "# SID namespace 1002001-1002999 is reserved for A2.\n"
        "# Rules that adapt an OWASP CRS detection carry 'owasp_crs_rule' metadata.\n\n"
        + "\n\n".join(record["rule"] for record in records) + "\n",
        encoding="utf-8",
    )
    print(f"Generated {len(records)} A2 scenarios and rules")


if __name__ == "__main__":
    main()
